syntacore/scr1/src/core/pipeline/scr1_pipe_top.sv 
syntacore/scr1/src/core/scr1_core_top.sv 
syntacore/scr1/src/core/scr1_dm.sv 
syntacore/scr1/src/core/scr1_tapc_synchronizer.sv 
syntacore/scr1/src/core/scr1_clk_ctrl.sv 
syntacore/scr1/src/core/scr1_scu.sv 
syntacore/scr1/src/core/scr1_tapc.sv 
syntacore/scr1/src/core/scr1_tapc_shift_reg.sv 
syntacore/scr1/src/core/scr1_dmi.sv 
syntacore/scr1/src/core/primitives/scr1_reset_cells.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_ifu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_idu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_exu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_mprf.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_csr.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_ialu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_lsu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_hdu.sv 
syntacore/scr1/src/core/pipeline/scr1_pipe_tdu.sv 
syntacore/scr1/src/core/pipeline/scr1_ipic.sv 
syntacore/scr1/src/top/scr1_dmem_router.sv 
syntacore/scr1/src/top/scr1_imem_router.sv 
syntacore/scr1/src/top/scr1_dp_memory.sv 
syntacore/scr1/src/top/scr1_tcm.sv 
syntacore/scr1/src/top/scr1_timer.sv 
syntacore/scr1/src/top/scr1_dmem_ahb.sv 
syntacore/scr1/src/top/scr1_imem_ahb.sv 
syntacore/scr1/src/top/scr1_top_axi.sv 
syntacore/scr1/src/top/scr1_mem_axi.sv
syntacore/scr1/src/core/pipeline/scr1_tracelog.sv
axi_crossbar/src/axi_arbitor.v
axi_crossbar/src/axi_crossbar_addr.v
axi_crossbar/src/axi_crossbar_rd.v
axi_crossbar/src/axi_crossbar.v
axi_crossbar/src/axi_crossbar_wr.v
axi_crossbar/src/axi_priority_encoder.v
axi_crossbar/src/axi_register_rd.v
axi_crossbar/src/axi_register_wr.v
axi_crossbar/src/pyfive_axi_crossbar.v
axi_spi_master/src/axi_spi_master.sv
axi_spi_master/src/spi_master_axi_if.sv
axi_spi_master/src/spi_master_clkgen.sv
axi_spi_master/src/spi_master_controller.sv
axi_spi_master/src/spi_master_fifo.sv
axi_spi_master/src/spi_master_rx.sv
axi_spi_master/src/spi_master_tx.sv
digital_core/digital_core.sv
